name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: .tool-versions

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        if: ${{ success() || failure() }}
        run: yarn lint

      - name: Test
        if: ${{ success() || failure() }}
        run: yarn test
